/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdhererRouteImport } from './routes/adherer'
import { Route as ConditionsGeneralesAdhesionPaiementRouteImport } from './routes/conditions-generales-adhesion-paiement'
import { Route as ConditionsGeneralesUtilisationRouteImport } from './routes/conditions-generales-utilisation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevenirPartenaireRouteImport } from './routes/devenir-partenaire'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as GpfBusinessConnectRouteImport } from './routes/gpf-business-connect'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as CommissionsIndexRouteImport } from './routes/commissions.index'
import { Route as CommissionsIntelligenceArtificielleRouteImport } from './routes/commissions.intelligence-artificielle'
import { Route as EvenementsIndexRouteImport } from './routes/evenements.index'
import { Route as EvenementsSlugRouteImport } from './routes/evenements.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhererRoute = AdhererRouteImport.update({
  id: '/adherer',
  path: '/adherer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesAdhesionPaiementRoute =
  ConditionsGeneralesAdhesionPaiementRouteImport.update({
    id: '/conditions-generales-adhesion-paiement',
    path: '/conditions-generales-adhesion-paiement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConditionsGeneralesUtilisationRoute =
  ConditionsGeneralesUtilisationRouteImport.update({
    id: '/conditions-generales-utilisation',
    path: '/conditions-generales-utilisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirPartenaireRoute = DevenirPartenaireRouteImport.update({
  id: '/devenir-partenaire',
  path: '/devenir-partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const GpfBusinessConnectRoute = GpfBusinessConnectRouteImport.update({
  id: '/gpf-business-connect',
  path: '/gpf-business-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsIndexRoute = CommissionsIndexRouteImport.update({
  id: '/commissions/',
  path: '/commissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsIntelligenceArtificielleRoute =
  CommissionsIntelligenceArtificielleRouteImport.update({
    id: '/commissions/intelligence-artificielle',
    path: '/commissions/intelligence-artificielle',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvenementsIndexRoute = EvenementsIndexRouteImport.update({
  id: '/evenements/',
  path: '/evenements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsSlugRoute = EvenementsSlugRouteImport.update({
  id: '/evenements/$slug',
  path: '/evenements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adherer': typeof AdhererRoute
  '/conditions-generales-adhesion-paiement': typeof ConditionsGeneralesAdhesionPaiementRoute
  '/conditions-generales-utilisation': typeof ConditionsGeneralesUtilisationRoute
  '/contact': typeof ContactRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/equipe': typeof EquipeRoute
  '/gpf-business-connect': typeof GpfBusinessConnectRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/commissions/intelligence-artificielle': typeof CommissionsIntelligenceArtificielleRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/commissions/': typeof CommissionsIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adherer': typeof AdhererRoute
  '/conditions-generales-adhesion-paiement': typeof ConditionsGeneralesAdhesionPaiementRoute
  '/conditions-generales-utilisation': typeof ConditionsGeneralesUtilisationRoute
  '/contact': typeof ContactRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/equipe': typeof EquipeRoute
  '/gpf-business-connect': typeof GpfBusinessConnectRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/commissions/intelligence-artificielle': typeof CommissionsIntelligenceArtificielleRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/commissions': typeof CommissionsIndexRoute
  '/evenements': typeof EvenementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adherer': typeof AdhererRoute
  '/conditions-generales-adhesion-paiement': typeof ConditionsGeneralesAdhesionPaiementRoute
  '/conditions-generales-utilisation': typeof ConditionsGeneralesUtilisationRoute
  '/contact': typeof ContactRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/equipe': typeof EquipeRoute
  '/gpf-business-connect': typeof GpfBusinessConnectRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/commissions/intelligence-artificielle': typeof CommissionsIntelligenceArtificielleRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/commissions/': typeof CommissionsIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adherer'
    | '/conditions-generales-adhesion-paiement'
    | '/conditions-generales-utilisation'
    | '/contact'
    | '/devenir-partenaire'
    | '/equipe'
    | '/gpf-business-connect'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-de-confidentialite'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/commissions/intelligence-artificielle'
    | '/evenements/$slug'
    | '/actualites/'
    | '/commissions/'
    | '/evenements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adherer'
    | '/conditions-generales-adhesion-paiement'
    | '/conditions-generales-utilisation'
    | '/contact'
    | '/devenir-partenaire'
    | '/equipe'
    | '/gpf-business-connect'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-de-confidentialite'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/commissions/intelligence-artificielle'
    | '/evenements/$slug'
    | '/actualites'
    | '/commissions'
    | '/evenements'
  id:
    | '__root__'
    | '/'
    | '/adherer'
    | '/conditions-generales-adhesion-paiement'
    | '/conditions-generales-utilisation'
    | '/contact'
    | '/devenir-partenaire'
    | '/equipe'
    | '/gpf-business-connect'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-de-confidentialite'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/commissions/intelligence-artificielle'
    | '/evenements/$slug'
    | '/actualites/'
    | '/commissions/'
    | '/evenements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdhererRoute: typeof AdhererRoute
  ConditionsGeneralesAdhesionPaiementRoute: typeof ConditionsGeneralesAdhesionPaiementRoute
  ConditionsGeneralesUtilisationRoute: typeof ConditionsGeneralesUtilisationRoute
  ContactRoute: typeof ContactRoute
  DevenirPartenaireRoute: typeof DevenirPartenaireRoute
  EquipeRoute: typeof EquipeRoute
  GpfBusinessConnectRoute: typeof GpfBusinessConnectRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenairesRoute: typeof PartenairesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  CommissionsIntelligenceArtificielleRoute: typeof CommissionsIntelligenceArtificielleRoute
  EvenementsSlugRoute: typeof EvenementsSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  CommissionsIndexRoute: typeof CommissionsIndexRoute
  EvenementsIndexRoute: typeof EvenementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adherer': {
      id: '/adherer'
      path: '/adherer'
      fullPath: '/adherer'
      preLoaderRoute: typeof AdhererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales-adhesion-paiement': {
      id: '/conditions-generales-adhesion-paiement'
      path: '/conditions-generales-adhesion-paiement'
      fullPath: '/conditions-generales-adhesion-paiement'
      preLoaderRoute: typeof ConditionsGeneralesAdhesionPaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales-utilisation': {
      id: '/conditions-generales-utilisation'
      path: '/conditions-generales-utilisation'
      fullPath: '/conditions-generales-utilisation'
      preLoaderRoute: typeof ConditionsGeneralesUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-partenaire': {
      id: '/devenir-partenaire'
      path: '/devenir-partenaire'
      fullPath: '/devenir-partenaire'
      preLoaderRoute: typeof DevenirPartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpf-business-connect': {
      id: '/gpf-business-connect'
      path: '/gpf-business-connect'
      fullPath: '/gpf-business-connect'
      preLoaderRoute: typeof GpfBusinessConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions/': {
      id: '/commissions/'
      path: '/commissions'
      fullPath: '/commissions/'
      preLoaderRoute: typeof CommissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions/intelligence-artificielle': {
      id: '/commissions/intelligence-artificielle'
      path: '/commissions/intelligence-artificielle'
      fullPath: '/commissions/intelligence-artificielle'
      preLoaderRoute: typeof CommissionsIntelligenceArtificielleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements/': {
      id: '/evenements/'
      path: '/evenements'
      fullPath: '/evenements/'
      preLoaderRoute: typeof EvenementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements/$slug': {
      id: '/evenements/$slug'
      path: '/evenements/$slug'
      fullPath: '/evenements/$slug'
      preLoaderRoute: typeof EvenementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdhererRoute: AdhererRoute,
  ConditionsGeneralesAdhesionPaiementRoute:
    ConditionsGeneralesAdhesionPaiementRoute,
  ConditionsGeneralesUtilisationRoute: ConditionsGeneralesUtilisationRoute,
  ContactRoute: ContactRoute,
  DevenirPartenaireRoute: DevenirPartenaireRoute,
  EquipeRoute: EquipeRoute,
  GpfBusinessConnectRoute: GpfBusinessConnectRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenairesRoute: PartenairesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  CommissionsIntelligenceArtificielleRoute:
    CommissionsIntelligenceArtificielleRoute,
  EvenementsSlugRoute: EvenementsSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  CommissionsIndexRoute: CommissionsIndexRoute,
  EvenementsIndexRoute: EvenementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
